
spring:
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/redisstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true # systemOut
        format_sql: true # logger
    #        use_sql_comments: true # jpql ??
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging.level:
  org.hibernate.SQL: debug
  org.springframework.cache: trace

server:
  port: 8080