with GOODS (GOODS_NO, ITM_NO, SUP_PCOST, SALE_PRC, STD_CATE, BRAND_NO, ENTR_NO, CHNL_NO, MK_DP_NO) AS MATERIALIZED (
SELECT CAST(SPLIT_PART(T, '|', 1) AS VARCHAR(20)) AS GOODS_NO
     , CAST(SPLIT_PART(T, '|', 2) AS VARCHAR(3)) AS ITEM_NO
     , CAST(SPLIT_PART(T, '|', 3) AS NUMERIC) AS SUP_PCOST
     , CAST(SPLIT_PART(T, '|', 4) AS NUMERIC) AS SALE_PRC
     , CAST(SPLIT_PART(T, '|', 5) AS VARCHAR(30)) AS STD_CATE
     , CAST(SPLIT_PART(T, '|', 6) AS VARCHAR(30)) AS BRAND_NO
     , CAST(SPLIT_PART(T, '|', 7) AS VARCHAR(30)) AS ENTR_NO
     , CAST(SPLIT_PART(T, '|', 8) AS VARCHAR(30)) AS CHNL_NO
     , CAST(SPLIT_PART(T, '|', 9) AS VARCHAR(30)) AS MK_DP_NO
FROM UNNEST(ARRAY['11954193|001|85000|100000|HT01020000|11115|1000002|1|1']) T
    ),
        USABLE_PROMO_BASE AS MATERIALIZED(
				SELECT PROMO_NO
				  FROM CC_PROM_BASE PB
				 WHERE 1=1
				   /* 쿠폰만 조회 */
				   AND PB.PROMO_TYP_CD = '11'
				   /* 쿠폰상태 진행 여부 체크 */
				   AND PB.PROMO_STAT_CD = '10'
				   /* 쿠폰/프로모션 등급 적용 체크 */
				   AND (
				   	   EXISTS(SELECT 1 FROM CC_PROMO_APLY_GRADE_INFO GRADE WHERE PB.PROMO_NO = GRADE.PROMO_NO AND GRADE.MBR_GRADE_CD = '10')
				   	   OR NOT EXISTS(SELECT 1 FROM CC_PROMO_APLY_GRADE_INFO GRADE WHERE PB.PROMO_NO = GRADE.PROMO_NO)
				   )
				   /* 유효기간 체크 */
				   AND now() BETWEEN PB.PROMO_STR_DTM AND PB.PROMO_END_DTM
				   /* 프로로션 발급 방식 체크*/
				   AND PB.ISSU_METH_CD IN ('03', '04')
				   /* 고정판촉쿠폰만 발급 */
				   AND PB.ISSU_SUB_CD = '01'
				   /* 쿠폰 발급일자 유효성 체크 */
				   AND CASE
				   	   WHEN PB.APLY_TERM_GB_CD = '01'
				   		    THEN now() BETWEEN TO_TIMESTAMP(CONCAT(PB.USE_PSB_STR_DT, ' 00:00:00'), 'YYYYMMDD HH24:MI:SS') AND TO_TIMESTAMP(CONCAT(PB.USE_PSB_END_DT, ' 23:59:59.999999'), 'YYYYMMDD HH24:MI:SS')
				   ELSE TRUE END
			), CPN_ISU_INFO AS (
				SELECT CPN_NO
					 , COUNT(0) TOT_CNT
					 , COUNT(CASE WHEN MBR_NO = '100000631' THEN 0 ELSE NULL END) MBR_CNT
				  FROM CC_CPN_ISU_MBR CI
				 WHERE 1=1
				   AND CI.CPN_NO IN (
					   SELECT UPB.PROMO_NO
					     FROM USABLE_PROMO_BASE UPB
					    INNER JOIN CC_PROM_BASE CP ON CP.PROMO_NO = UPB.PROMO_NO
					    WHERE 1=1
					      AND (CP.ID_ISSU_LMT_YN = 'Y' OR CP.TOT_CPN_ISSU_LMT_YN = 'Y')
				   )
				   AND CI.ORG_CPN_ISU_NO IS NULL
				 GROUP BY CPN_NO
			),
			PROMO_BASE AS MATERIALIZED(
			SELECT PB.*
				 , 0 ISSU_POSIBLE_CNT
			FROM CC_PROM_BASE PB
			WHERE 1=1
			/* 쿠폰만 조회 */
			AND PB.PROMO_TYP_CD = '11'
			/* 쿠폰상태 진행 여부 체크 */
			AND PB.PROMO_STAT_CD = '10'
			/* 타임쿠폰일 경우 시간 체크 */
			AND CASE
				WHEN PB.TM_CPN_YN = 'Y'
					THEN TO_CHAR(now(), 'HH24MI') BETWEEN USE_PSB_STR_TM AND USE_PSB_END_TM
				ELSE TRUE
			END
			/* 사용가능요일 체크 */
			AND (
				EXISTS (SELECT 1 FROM CC_PROMO_USE_WDAY_INFO CPUWI WHERE PROMO_NO = PB.PROMO_NO AND CPUWI.USE_WDAY_CD = CAST(EXTRACT(ISODOW FROM now()) AS CHAR))
				OR NOT EXISTS (SELECT 1 FROM CC_PROMO_USE_WDAY_INFO CPUWI WHERE PROMO_NO = PB.PROMO_NO)
			)
			/* 쿠폰/프로모션 등급 적용 체크 */
			AND (
				EXISTS(SELECT 1 FROM CC_PROMO_APLY_GRADE_INFO GRADE WHERE PB.PROMO_NO = GRADE.PROMO_NO AND GRADE.MBR_GRADE_CD = '10')
				OR NOT EXISTS(SELECT 1 FROM CC_PROMO_APLY_GRADE_INFO GRADE WHERE PB.PROMO_NO = GRADE.PROMO_NO)
			)
			/* 사용가능 쿠폰 체크 */
			AND EXISTS(SELECT 1 FROM CC_CPN_ISU_MBR CI WHERE PB.PROMO_NO = CI.CPN_NO AND CI.MBR_NO = '100000631' AND CI.USE_YN = 'N' AND now() BETWEEN CI.VALI_STRT_DTM AND CI.VALI_END_DTM)
			UNION ALL
			SELECT PB.*
				 , 0 ISSU_POSIBLE_CNT
			FROM CC_PROM_BASE PB
			WHERE 1=1
			/* 임직원 할인 조회 */
			AND PB.PROMO_TYP_CD = '20'
			/* 쿠폰상태 진행 여부 체크 */
			AND PB.PROMO_STAT_CD = '10'
			/* 프로모션 기간 유효성 체크 */
			AND now() BETWEEN PB.PROMO_STR_DTM AND PROMO_END_DTM
			UNION ALL
			SELECT PB.*
				 , 0 ISSU_POSIBLE_CNT
			FROM CC_PROM_BASE PB
			WHERE 1=1
			/* 상품즉시할인 조회 */
			AND PB.PROMO_TYP_CD = '21'
			/* 쿠폰상태 진행 여부 체크 */
			AND PB.PROMO_STAT_CD = '10'
			/* 프로모션 기간 유효성 체크 */
			AND now() BETWEEN PB.PROMO_STR_DTM AND PROMO_END_DTM
			/* 쿠폰/프로모션 등급 적용 체크 */
			AND (
		    (SELECT COUNT(0) CNT FROM ST_STD_CD WHERE GRP_CD = 'ME008' AND USE_YN = 'Y') = (SELECT COUNT(0) FROM CC_PROMO_APLY_GRADE_INFO GRADE WHERE PB.PROMO_NO = GRADE.PROMO_NO)
			OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_GRADE_INFO GRADE WHERE PB.PROMO_NO = GRADE.PROMO_NO)
		)
		/* 상품상세의 경우 다운로드 가능한 쿠폰이면 사용 가능 쿠폰으로 계산한다. */
			UNION ALL
			SELECT PB.*
				 , LEAST(
					CASE
						WHEN PB.TOT_CPN_ISSU_LMT_YN = 'N' THEN 9999999
						ELSE PB.TOT_CPN_ISSU_QTY - COALESCE(CII.TOT_CNT, 0)
					END
					, CASE
						WHEN PB.ID_ISSU_LMT_YN = 'N' THEN 9999999
						ELSE PB.ID_ISSU_QTY - COALESCE(CII.MBR_CNT, 0)
					END
					, (SELECT COUNT(0) FROM GOODS)
				 )
			  FROM CC_PROM_BASE PB
			  LEFT JOIN CPN_ISU_INFO CII ON PB.PROMO_NO = CII.CPN_NO
			 WHERE 1=1
			   AND PB.PROMO_NO IN (SELECT PROMO_NO FROM USABLE_PROMO_BASE)
			   /* 전체 발급 횟 수 제한 체크 */
			   AND (
			       PB.TOT_CPN_ISSU_LMT_YN = 'N'
			       OR (COALESCE(CII.TOT_CNT, 0) < PB.TOT_CPN_ISSU_QTY)
			   )
			   /* 아이디 발급 횟 수 제한 체크 */
			   AND (
			       PB.ID_ISSU_LMT_YN = 'N'
			       OR (COALESCE(CII.MBR_CNT, 0) < PB.ID_ISSU_QTY)
			   )
			   ),
			   PROMO_APLY_INFO AS MATERIALIZED (
			SELECT GOODS.GOODS_NO,GOODS.ITM_NO,GOODS.SUP_PCOST,GOODS.SALE_PRC,GOODS.STD_CATE,GOODS.BRAND_NO,GOODS.ENTR_NO,GOODS.CHNL_NO
				 , PB.PROMO_NO
				 , PB.PROMO_TYP_CD
				 , PB.OUR_CHRG_RATE
				 , PB.ENTR_CHRG_RATE
				 , PB.FIXAMT_FXRT_GB_CD
				 , PB.DC_RATE_AMT
				 , PB.MIN_BUY_QTY
				 , PB.MIN_BUY_AMT
				 , PB.MAX_DC_AMT
				 , PB.APLY_LMT_DC_RATE
				 , PB.ISSU_POSIBLE_CNT
				 , PB.APLY_TERM_GB_CD
				 , PB.ISSU_DD_STD_CPN_USE_DDS
				 , PB.USE_PSB_STR_DT
				 , PB.USE_PSB_END_DT
              FROM GOODS
             CROSS JOIN PROMO_BASE PB
             WHERE 1=1
			/* 적용대상 - 사이트 */
		  AND (
			  EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD='01' AND CPAI.FVR_APLY_TYP_CD='01' AND CPAI.FVR_TGT_NO= '1')
			  OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD='01' AND CPAI.FVR_APLY_TYP_CD='01')
		  )
		  /* 적용대상 - 상품 */
		  AND (
			   EXISTS (
				   SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '02' AND CPAI.FVR_TGT_NO = GOODS.GOODS_NO
			   )
			   OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '02')
		  )
		  /* 적용대상 - 표준카테고리 */
		  AND (
			   EXISTS (
				   SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '04' AND CPAI.FVR_TGT_NO = GOODS.STD_CATE
			   )
			   OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '04')
		  )
		  /* 적용대상 - 전시카테고리 */
		  AND (
			   EXISTS (
				   SELECT 1
					 FROM CC_PROMO_APLY_INFO CPAI
					WHERE PB.PROMO_NO = CPAI.PROMO_NO
					  AND CPAI.FVR_APLY_GB_CD = '01'
					  AND CPAI.FVR_APLY_TYP_CD = '03'
					  AND EXISTS (
						  SELECT GI.DISP_CTG_NO
							FROM PR_DISP_GOODS_INFO GI
						   INNER JOIN PR_DISP_CTG_BASE BASE ON BASE.DISP_CTG_NO = GI.DISP_CTG_NO
						   WHERE 1=1
							 AND BASE.USE_YN = 'Y'
							 AND GI.DISP_YN = 'Y'
							 AND GOODS_NO = GOODS.GOODS_NO
							 AND CPAI.FVR_TGT_NO = GI.DISP_CTG_NO LIMIT 1
					   )
			   )
			   OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '03')
		  )
		  /* 적용대상 - 브랜드 */
		  AND (
			   EXISTS (
				   SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '06' AND CPAI.FVR_TGT_NO = GOODS.BRAND_NO
			   )
			   OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '06')
		  )
		  /* 적용대상 - 협력사 */
		  AND (
			   EXISTS (
				   SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '05' AND CPAI.FVR_TGT_NO = GOODS.ENTR_NO
			   )
			   OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '05')
		  )
		  /* 적용대상 - 채널 */
		  AND (
			   EXISTS (
				   SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '07' AND CPAI.FVR_TGT_NO = GOODS.CHNL_NO
			   )
			   OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '07')
		  )
		  /* 적용대상 - 기획전(주문시에만 체크) */
		  AND (
		  		EXISTS (
			  		SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '09' AND CPAI.FVR_TGT_NO = GOODS.MK_DP_NO
			  	)
			  	OR NOT EXISTS (SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '01' AND CPAI.FVR_APLY_TYP_CD = '09')
		  )
		  /* 제외대상 - 상품 */
		  AND NOT EXISTS (
			  SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '02' AND CPAI.FVR_APLY_TYP_CD = '02' AND CPAI.FVR_TGT_NO = GOODS.GOODS_NO
		  )
		  /* 제외대상 - 표준카테고리 */
		  AND NOT EXISTS (
			  SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '02' AND CPAI.FVR_APLY_TYP_CD = '04' AND CPAI.FVR_TGT_NO = GOODS.STD_CATE
		  )
		  /* 제외대상 - 브랜드 */
		  AND NOT EXISTS (
			  SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '02' AND CPAI.FVR_APLY_TYP_CD = '06' AND CPAI.FVR_TGT_NO = GOODS.BRAND_NO
		  )
		  /* 제외대상 - 협력사 */
		  AND NOT EXISTS (
		 	  SELECT 1 FROM CC_PROMO_APLY_INFO CPAI WHERE PROMO_NO = PB.PROMO_NO AND CPAI.FVR_APLY_GB_CD = '02' AND CPAI.FVR_APLY_TYP_CD = '05' AND CPAI.FVR_TGT_NO = GOODS.ENTR_NO
		  )
			  AND CASE WHEN PB.PROMO_TYP_CD != '12' THEN (
				  (PB.FIXAMT_FXRT_GB_CD = '01' AND ((GOODS.SALE_PRC - PB.DC_RATE_AMT) >= GOODS.SUP_PCOST))
				  OR (PB.FIXAMT_FXRT_GB_CD = '02' AND (GOODS.SALE_PRC - ROUND(GOODS.SALE_PRC * PB.DC_RATE_AMT / 100) >= GOODS.SUP_PCOST))
			  ) ELSE TRUE END
			  AND CASE WHEN PB.PROMO_TYP_CD IN ('11','13') THEN (
				  GOODS.SALE_PRC >= PB.MIN_BUY_AMT
			  ) ELSE TRUE END
        ), CPN_ISU_LIST AS MATERIALIZED(
			SELECT CPN_NO
				 , MBR_NO
				 , CPN_ISU_NO
				 , CPN_ISU_DTM
				 , VALI_STRT_DTM
				 , VALI_END_DTM
				 , USE_YN
				 , ROW_NUMBER() OVER(PARTITION BY CPN_NO ORDER BY VALI_END_DTM DESC, CPN_ISU_NO ASC) RN
			  FROM CC_CPN_ISU_MBR CI
			 WHERE 1=1
			   AND CPN_NO IN (SELECT PROMO_NO FROM PROMO_APLY_INFO)
			   AND MBR_NO = '100000631'
			   AND USE_YN = 'N'
			   AND now() BETWEEN CI.VALI_STRT_DTM AND CI.VALI_END_DTM
		)

SELECT GOODS_NO
     , ITM_NO
     , SUP_PCOST
     , SALE_PRC
     , PAI.PROMO_NO
     , ML.PROMO_NM
     , PROMO_TYP_CD
     , OUR_CHRG_RATE
     , ENTR_CHRG_RATE
     , FIXAMT_FXRT_GB_CD
     , DC_RATE_AMT
     , MIN_BUY_QTY
     , MIN_BUY_AMT
     , MAX_DC_AMT
     , APLY_LMT_DC_RATE
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.CPN_ISU_NO ELSE CI.CPN_ISU_NO END CPN_ISU_NO
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.MBR_NO ELSE CI.MBR_NO END MBR_NO
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.CPN_NO ELSE CI.CPN_NO END CPN_NO
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.CPN_ISU_DTM ELSE CI.CPN_ISU_DTM END CPN_ISU_DTM
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.VALI_STRT_DTM ELSE CI.VALI_STRT_DTM END VALI_STRT_DTM
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.VALI_END_DTM ELSE CI.VALI_END_DTM END VALI_END_DTM
     , CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.USE_YN ELSE CI.USE_YN END USE_YN
FROM PROMO_APLY_INFO PAI
         LEFT JOIN CC_PROM_BASE_ML ML ON PAI.PROMO_NO = ML.PROMO_NO AND ML.LANG_CD = 'ko'
         LEFT JOIN CPN_ISU_LIST CI ON PAI.PROMO_NO = CI.CPN_NO AND CI.RN <= (SELECT COUNT(0) FROM GOODS)
         LEFT JOIN (
    SELECT 'TEMP_' || GS CPN_ISU_NO
         , '100000631' MBR_NO
         , PAI.PROMO_NO CPN_NO
         , now()::TIMESTAMP CPN_ISU_DTM
						, CASE
                                              WHEN PAI.APLY_TERM_GB_CD = '02' THEN now()::DATE
							ELSE TO_TIMESTAMP(CONCAT(PAI.USE_PSB_STR_DT, ' 00:00:00'), 'YYYYMMDD HH24:MI:SS')::TIMESTAMP
						END VALI_STRT_DTM
						, CASE
							WHEN PAI.APLY_TERM_GB_CD = '02'
								THEN now()::DATE + CONCAT(1 + PAI.ISSU_DD_STD_CPN_USE_DDS, ' DAY')::INTERVAL - '0.001 MILLISECOND'::INTERVAL
							ELSE TO_TIMESTAMP(concat(pai.use_psb_end_dt, ' 23:59:59.999999'), 'YYYYMMDD hh24:mi:ss')::TIMESTAMP
						END VALI_END_DTM
						, 'N' USE_YN
						, GS as LV
    FROM (
        SELECT DISTINCT PROMO_NO
            , PB.APLY_LMT_DC_RATE
            , PB.ISSU_POSIBLE_CNT
            , PB.APLY_TERM_GB_CD
            , PB.ISSU_DD_STD_CPN_USE_DDS
            , PB.USE_PSB_STR_DT
            , PB.USE_PSB_END_DT
        FROM PROMO_APLY_INFO PB
        WHERE 1=1
        AND PB.ISSU_POSIBLE_CNT > 0
        ) PAI
        CROSS JOIN GENERATE_SERIES(1, PAI.ISSU_POSIBLE_CNT) GS
) GS ON GS.CPN_NO = PAI.PROMO_NO AND PAI.ISSU_POSIBLE_CNT > 0
WHERE 1=1
  AND CASE WHEN PROMO_TYP_CD IN ('11','12','13') THEN CASE WHEN PAI.ISSU_POSIBLE_CNT > 0 THEN GS.CPN_ISU_NO ELSE CI.CPN_ISU_NO END IS NOT NULL ELSE TRUE END
ORDER BY SALE_PRC DESC, GOODS_NO, ITM_NO, CI.VALI_END_DTM, PROMO_NO
;